var QuadChunk=function(a){var d=this;d.initialize=function(){d.quadBlocks=[];d.remaining=16384;d.dirty=!1};d.allocate=function(){d.geometry=new THREE.BufferGeometry;d.geometry.dynamic=!0;var c=16384-d.remaining;d.geometry.attributes={index:{itemSize:1,array:new Int16Array(6*c),numItems:6*c},position:{itemSize:3,array:new Float32Array(12*c),numItems:12*c},normal:{itemSize:3,array:new Float32Array(12*c),numItems:12*c},color:{itemSize:3,array:new Float32Array(12*c),numItems:12*c}};for(var b=d.geometry.attributes.index.array,
i=0;i<c;i++){var f=4*i,l=6*i;b[l+0]=f+0;b[l+1]=f+1;b[l+2]=f+3;b[l+3]=f+1;b[l+4]=f+2;b[l+5]=f+3}d.geometry.offsets=[{start:0,count:6*c,index:0}];d.mesh=new THREE.Mesh(d.geometry,a);d.geometry.boundingSphere.radius=1E300};d.addQuadBlock=function(a){if(a.size>d.remaining)return!1;d.quadBlocks.push(a);a.quadChunk=d;d.remaining-=a.size;return d.dirty=!0};d.releaseQuadBlock=function(a){var b=d.quadBlocks.indexOf(a);d.quadBlocks.splice(b,1);d.remaining+=a.size;d.dirty=!0};d.build=function(){d.allocate();
for(var a=d.geometry.attributes.position.array,b=d.geometry.attributes.normal.array,i=d.geometry.attributes.color.array,f=0,l=0;l<d.quadBlocks.length;l++)for(var k=d.quadBlocks[l],e=k.quads,m=0;m<k.size;m++){var g=12*f,h=27*m;a[g+0]=e[h+0];a[g+1]=e[h+1];a[g+2]=e[h+2];a[g+3]=e[h+3];a[g+4]=e[h+4];a[g+5]=e[h+5];a[g+6]=e[h+6];a[g+7]=e[h+7];a[g+8]=e[h+8];a[g+9]=e[h+9];a[g+10]=e[h+10];a[g+11]=e[h+11];i[g+0]=e[h+12];i[g+1]=e[h+13];i[g+2]=e[h+14];i[g+3]=e[h+15];i[g+4]=e[h+16];i[g+5]=e[h+17];i[g+6]=e[h+18];
i[g+7]=e[h+19];i[g+8]=e[h+20];i[g+9]=e[h+21];i[g+10]=e[h+22];i[g+11]=e[h+23];b[g+0]=e[h+24];b[g+1]=e[h+25];b[g+2]=e[h+26];b[g+3]=e[h+24];b[g+4]=e[h+25];b[g+5]=e[h+26];b[g+6]=e[h+24];b[g+7]=e[h+25];b[g+8]=e[h+26];b[g+9]=e[h+24];b[g+10]=e[h+25];b[g+11]=e[h+26];f+=1}d.dirty=!1};d.initialize()},QuadBlock=function(a,d){var c=this;c.initialize=function(){c.manager=a;c.quadChunk=null;c.size=d;c.index=0;c.quads=new Float32Array(27*c.size)};c.addQuad=function(a,i,f,d,k,e,m,g,h,r,j,p,q,t,u,v,w,x,y,z,A,B,C,
D){if(c.index>=27*c.size)console.log("ERROR: tried to add to quad block past its length.");else{var n=new THREE.Vector3(d-a,k-i,e-f),s=new THREE.Vector3(m-a,g-i,h-f);n.crossSelf(s);n.normalize();var s=n.x,E=n.y,n=n.z;c.quads[c.index+0]=a;c.quads[c.index+1]=i;c.quads[c.index+2]=f;c.quads[c.index+3]=d;c.quads[c.index+4]=k;c.quads[c.index+5]=e;c.quads[c.index+6]=m;c.quads[c.index+7]=g;c.quads[c.index+8]=h;c.quads[c.index+9]=r;c.quads[c.index+10]=j;c.quads[c.index+11]=p;c.quads[c.index+12]=q;c.quads[c.index+
13]=t;c.quads[c.index+14]=u;c.quads[c.index+15]=v;c.quads[c.index+16]=w;c.quads[c.index+17]=x;c.quads[c.index+18]=y;c.quads[c.index+19]=z;c.quads[c.index+20]=A;c.quads[c.index+21]=B;c.quads[c.index+22]=C;c.quads[c.index+23]=D;c.quads[c.index+24]=s;c.quads[c.index+25]=E;c.quads[c.index+26]=n;c.index+=27}};c.release=function(){c.quadChunk.releaseQuadBlock(c);c.manager.releaseQuadBlock(c);delete c.quads};c.initialize()},QuadManager=function(){var a=this;a.initialize=function(){a.quadChunks=[];a.quadBlocks=
[];a.material=new THREE.MeshPhongMaterial({color:16777215,vertexColors:THREE.VertexColors});a.mesh=new THREE.Mesh(new THREE.Geometry)};a.getQuadBlock=function(d){if(16384<d)console.log("ERROR: tried to request a QuadBlock of too great a size.");else{for(var d=new QuadBlock(a,d),c=!1,b=0;b<a.quadChunks.length&&!(c=a.quadChunks[b].addQuadBlock(d));b++);c||(c=new QuadChunk(a.material),a.quadChunks.push(c),c.addQuadBlock(d));a.quadBlocks.push(d);return d}};a.releaseQuadBlock=function(d){d=a.quadBlocks.indexOf(d);
a.quadBlocks.splice(d,1)};a.update=function(){for(var d=a.mesh.children.slice(),c=0;c<d.length;c++)a.mesh.remove(d[c]);for(c=0;c<a.quadChunks.length;c++)d=a.quadChunks[c],d.dirty&&d.build();for(c=0;c<a.quadChunks.length;c++)a.mesh.add(a.quadChunks[c].mesh)};a.initialize()};var Editor=function(){var a=this,d=function(){this.color=a.randomColor();this.res=7;this.tags="";this.clear=function(){a.widget={resolution:a.controls.res,blocks:{}};a.buildBlocks()};this.sciptorStatus=!1;this.toggleScriptor=function(){(this.scriptorStatus=!this.scriptorStatus)?($(a.scriptor).show(),$(a.scriptor).focus()):$(a.scriptor).hide()};this.runScript=function(){eval(a.scriptor.value)}};a.initialize=function(){a.activated=!1;a.div=document.getElementById("editorDiv");a.controlsDiv=document.getElementById("editorControlsDiv");
a.scriptor=document.getElementById("editorScriptor");a.renderCanvas=document.getElementById("editorRenderCanvas");$(a.div).hide();$(a.scriptor).hide();a.controls=new d;a.gui=new dat.GUI({autoplace:!1,width:195,hideable:!1});a.gui.addColor(a.controls,"color").listen().name("Color");a.gui.add(a.controls,"res",1,17).name("Resolution").step(1).onChange(function(){a.setResolution();a.buildBlocks()});a.gui.add(a.controls,"tags").listen().name("Tags");a.gui.add(a.controls,"clear").name("Clear Editor");a.gui.add(a.controls,
"toggleScriptor").name("Toggle Script");a.gui.add(a.controls,"runScript").name("Run Script");a.controlsDiv.appendChild(a.gui.domElement);a.swatches=[];for(var c=0;2>c;c++)for(var b=0;8>b;b++){var i=document.createElement("div");i.style.position="fixed";i.style.top=2+24*c;i.style.left=2+24*b;i.style.width=20;i.style.height=20;i.style.borderRadius=4;i.style.cursor="pointer";i.color=a.randomColor();i.style.background=i.color;i.style.border="1px solid black";a.controlsDiv.appendChild(i);a.swatches.push(i);
$(i).click(function(){a.controls.color=this.color})}a.mouse={down:!1,x:0,y:0};window.addEventListener("mousemove",a.onMouseMove,!1);window.addEventListener("mouseup",a.onMouseUp,!1);a.renderCanvas.addEventListener("mousedown",a.onMouseDown,!1);a.renderCanvas.addEventListener("DOMMouseScroll",a.onMouseWheel,!1);a.renderCanvas.addEventListener("mousewheel",a.onMouseWheel,!1);document.body.oncontextmenu=function(){return!1};a.helpShown=!0;$("#editorHelpIcon").click(function(){a.helpShown=!a.helpShown;
a.helpShown?$("#editorHelp").show():$("#editorHelp").hide()});$("#editorHelp").click(function(){a.helpShown=!a.helpShown;a.helpShown?$("#editorHelp").show():$("#editorHelp").hide()});$(window).resize(a.onResize);a.skyBoxTexture=THREE.ImageUtils.loadTexture("stars.png");a.skyBoxTexture.wrapS=a.skyBoxTexture.wrapT=THREE.RepeatWrapping;a.skyBoxTexture.repeat.set(2,2);a.frameMesh=null;a.skyBox=null;a.qm=new QuadManager;a.qb=null;a.widget={resolution:a.controls.res,blocks:{}};a.properWidget=null;a.ambientDepth=
0.25;a.scene=new THREE.Scene;a.scene.add(a.qm.mesh);a.camera=new THREE.PerspectiveCamera(60,a.renderCanvas.width/a.renderCanvas.height,0.125,4096);a.camera.up=new THREE.Vector3(0,0,1);a.camera.pan=new THREE.Vector3(0,0,-a.controls.res/4);a.camera.pitch=0.29;a.camera.yaw=-0.82;a.camera.targetPitch=a.camera.pitch;a.camera.targetYaw=a.camera.yaw;a.camera.zoom=2*a.controls.res;a.camera.targetZoom=a.camera.zoom;a.scene.add(a.camera);a.light=new THREE.PointLight(16777215,1);a.light.position=a.camera.position;
a.scene.add(a.light);a.setResolution();a.renderer=new THREE.WebGLRenderer({antialias:!0,canvas:a.renderCanvas});a.renderer.setSize(a.renderCanvas.width,a.renderCanvas.height);a.buildBlocks();a.onResize()};a.onResize=function(){a.renderCanvas.style.height=window.innerHeight;a.renderCanvas.style.width=window.innerWidth;a.renderCanvas.height=window.innerHeight;a.renderCanvas.width=window.innerWidth;a.renderer.setSize(window.innerWidth,window.innerHeight);a.camera.aspect=window.innerWidth/window.innerHeight;
a.camera.updateProjectionMatrix()};a.deactivate=function(){$(a.div).fadeOut(function(){a.activated=!1})};a.activate=function(){a.activated=!0;$(a.div).fadeIn();requestAnimationFrame(a.render)};a.randomColor=function(){var a=Math.floor(256*(0.9*Math.random()+0.1)),b=Math.floor(256*(0.9*Math.random()+0.1))<<8,i=Math.floor(256*(0.9*Math.random()+0.1))<<16;return"#"+(a+b+i).toString(16)};a.buildBlocks=function(){null!=a.qb&&a.qb.release();var c=6*_.keys(a.widget.blocks).length;a.qb=a.qm.getQuadBlock(c);
_.each(a.widget.blocks,function(b){var c=((b.color&16711680)>>16)/255,f=((b.color&65280)>>8)/255,d=(b.color&255)/255,k=1,e=1,m=1,g=1,h=1,r=1,j=1,p=1,q=1,t=1,u=1,v=1,w=1,x=1,y=1,z=1,A=1,B=1,C=1,D=1,n=1,s=1,E=1,F=1;[b.x-1,b.y+1,b.z+1]in a.widget.blocks&&(e-=a.ambientDepth,y-=a.ambientDepth,C-=a.ambientDepth);[b.x,b.y+1,b.z+1]in a.widget.blocks&&(e-=a.ambientDepth,m-=a.ambientDepth,B-=a.ambientDepth,C-=a.ambientDepth);[b.x+1,b.y+1,b.z+1]in a.widget.blocks&&(m-=a.ambientDepth,B-=a.ambientDepth,t-=a.ambientDepth);
[b.x-1,b.y+1,b.z]in a.widget.blocks&&(k-=a.ambientDepth,e-=a.ambientDepth,y-=a.ambientDepth,z-=a.ambientDepth);[b.x,b.y+1,b.z]in a.widget.blocks&&(k-=a.ambientDepth,e-=a.ambientDepth,m-=a.ambientDepth,g-=a.ambientDepth);[b.x+1,b.y+1,b.z]in a.widget.blocks&&(m-=a.ambientDepth,g-=a.ambientDepth,q-=a.ambientDepth,t-=a.ambientDepth);[b.x-1,b.y+1,b.z-1]in a.widget.blocks&&(k-=a.ambientDepth,s-=a.ambientDepth,z-=a.ambientDepth);[b.x,b.y+1,b.z-1]in a.widget.blocks&&(k-=a.ambientDepth,g-=a.ambientDepth,s-=
a.ambientDepth,E-=a.ambientDepth);[b.x+1,b.y+1,b.z-1]in a.widget.blocks&&(g-=a.ambientDepth,E-=a.ambientDepth,q-=a.ambientDepth);[b.x-1,b.y,b.z+1]in a.widget.blocks&&(C-=a.ambientDepth,D-=a.ambientDepth,x-=a.ambientDepth,y-=a.ambientDepth);[b.x,b.y,b.z+1]in a.widget.blocks&&(A-=a.ambientDepth,B-=a.ambientDepth,C-=a.ambientDepth,D-=a.ambientDepth);[b.x+1,b.y,b.z+1]in a.widget.blocks&&(A-=a.ambientDepth,B-=a.ambientDepth,t-=a.ambientDepth,u-=a.ambientDepth);[b.x-1,b.y,b.z]in a.widget.blocks&&(w-=a.ambientDepth,
x-=a.ambientDepth,y-=a.ambientDepth,z-=a.ambientDepth);[b.x+1,b.y,b.z]in a.widget.blocks&&(q-=a.ambientDepth,t-=a.ambientDepth,u-=a.ambientDepth,v-=a.ambientDepth);[b.x-1,b.y,b.z-1]in a.widget.blocks&&(n-=a.ambientDepth,s-=a.ambientDepth,w-=a.ambientDepth,z-=a.ambientDepth);[b.x,b.y,b.z-1]in a.widget.blocks&&(n-=a.ambientDepth,s-=a.ambientDepth,E-=a.ambientDepth,F-=a.ambientDepth);[b.x+1,b.y,b.z-1]in a.widget.blocks&&(E-=a.ambientDepth,F-=a.ambientDepth,q-=a.ambientDepth,v-=a.ambientDepth);[b.x-1,
b.y-1,b.z+1]in a.widget.blocks&&(D-=a.ambientDepth,x-=a.ambientDepth,j-=a.ambientDepth);[b.x,b.y-1,b.z+1]in a.widget.blocks&&(A-=a.ambientDepth,D-=a.ambientDepth,r-=a.ambientDepth,j-=a.ambientDepth);[b.x+1,b.y-1,b.z+1]in a.widget.blocks&&(A-=a.ambientDepth,u-=a.ambientDepth,r-=a.ambientDepth);[b.x-1,b.y-1,b.z]in a.widget.blocks&&(x-=a.ambientDepth,w-=a.ambientDepth,j-=a.ambientDepth,p-=a.ambientDepth);[b.x,b.y-1,b.z]in a.widget.blocks&&(h-=a.ambientDepth,r-=a.ambientDepth,j-=a.ambientDepth,p-=a.ambientDepth);
[b.x+1,b.y-1,b.z]in a.widget.blocks&&(h-=a.ambientDepth,r-=a.ambientDepth,u-=a.ambientDepth,v-=a.ambientDepth);[b.x-1,b.y-1,b.z-1]in a.widget.blocks&&(p-=a.ambientDepth,w-=a.ambientDepth,n-=a.ambientDepth);[b.x,b.y-1,b.z-1]in a.widget.blocks&&(n-=a.ambientDepth,F-=a.ambientDepth,h-=a.ambientDepth,p-=a.ambientDepth);[b.x+1,b.y-1,b.z-1]in a.widget.blocks&&(h-=a.ambientDepth,F-=a.ambientDepth,v-=a.ambientDepth);a.qb.addQuad(b.x-0.5,b.y+0.5,b.z-0.5,b.x-0.5,b.y+0.5,b.z+0.5,b.x+0.5,b.y+0.5,b.z+0.5,b.x+
0.5,b.y+0.5,b.z-0.5,c*k,f*k,d*k,c*e,f*e,d*e,c*m,f*m,d*m,c*g,f*g,d*g);a.qb.addQuad(b.x+0.5,b.y-0.5,b.z-0.5,b.x+0.5,b.y-0.5,b.z+0.5,b.x-0.5,b.y-0.5,b.z+0.5,b.x-0.5,b.y-0.5,b.z-0.5,c*h,f*h,d*h,c*r,f*r,d*r,c*j,f*j,d*j,c*p,f*p,d*p);a.qb.addQuad(b.x+0.5,b.y-0.5,b.z+0.5,b.x+0.5,b.y+0.5,b.z+0.5,b.x-0.5,b.y+0.5,b.z+0.5,b.x-0.5,b.y-0.5,b.z+0.5,c*A,f*A,d*A,c*B,f*B,d*B,c*C,f*C,d*C,c*D,f*D,d*D);a.qb.addQuad(b.x-0.5,b.y-0.5,b.z-0.5,b.x-0.5,b.y+0.5,b.z-0.5,b.x+0.5,b.y+0.5,b.z-0.5,b.x+0.5,b.y-0.5,b.z-0.5,c*n,f*n,
d*n,c*s,f*s,d*s,c*E,f*E,d*E,c*F,f*F,d*F);a.qb.addQuad(b.x+0.5,b.y+0.5,b.z-0.5,b.x+0.5,b.y+0.5,b.z+0.5,b.x+0.5,b.y-0.5,b.z+0.5,b.x+0.5,b.y-0.5,b.z-0.5,c*q,f*q,d*q,c*t,f*t,d*t,c*u,f*u,d*u,c*v,f*v,d*v);a.qb.addQuad(b.x-0.5,b.y-0.5,b.z-0.5,b.x-0.5,b.y-0.5,b.z+0.5,b.x-0.5,b.y+0.5,b.z+0.5,b.x-0.5,b.y+0.5,b.z-0.5,c*w,f*w,d*w,c*x,f*x,d*x,c*y,f*y,d*y,c*z,f*z,d*z)});a.qm.update()};a.pick=function(c,b,d){for(var c=new THREE.Vector2((c-a.renderCanvas.width/2)/(a.renderCanvas.width/2),-(b-a.renderCanvas.height/
2)/(a.renderCanvas.height/2)),f=(new THREE.Projector).pickingRay(c,a.camera),c=f.origin.x,b=f.origin.y,l=f.origin.z,k=f.direction.x,e=f.direction.y,f=f.direction.z,m=0.5*k/Math.abs(k),g=0.5*e/Math.abs(e),h=0.5*f/Math.abs(f),r=0;1024>r;){var j=Math.min((Math.floor(c)+0.5+m-c)/k,(Math.floor(b)+0.5+g-b)/e,(Math.floor(l)+0.5+h-l)/f),p=c+1.01*k*j,q=b+1.01*e*j,j=l+1.01*f*j;if(d){if(-0.5==Math.floor(j)+0.5&&0<Math.floor(c)+0.5&&Math.floor(c)+0.5<a.controls.res&&0<Math.floor(b)+0.5&&Math.floor(b)+0.5<a.controls.res&&
0<Math.floor(l)+0.5&&Math.floor(l)+0.5<a.controls.res)return[Math.floor(c)+0.5,Math.floor(b)+0.5,Math.floor(l)+0.5];if([Math.floor(p)+0.5,Math.floor(q)+0.5,Math.floor(j)+0.5]in a.widget.blocks){if(0<Math.floor(c)+0.5&&Math.floor(c)+0.5<a.controls.res&&0<Math.floor(b)+0.5&&Math.floor(b)+0.5<a.controls.res&&0<Math.floor(l)+0.5&&Math.floor(l)+0.5<a.controls.res)return[Math.floor(c)+0.5,Math.floor(b)+0.5,Math.floor(l)+0.5];break}}else if([Math.floor(p)+0.5,Math.floor(q)+0.5,Math.floor(j)+0.5]in a.widget.blocks)return[Math.floor(p)+
0.5,Math.floor(q)+0.5,Math.floor(j)+0.5];c=p;b=q;l=j;r++}return null};a.setResolution=function(){a.scene.remove(a.frameMesh);var c=new THREE.CubeGeometry(a.controls.res,a.controls.res,a.controls.res),b=new THREE.MeshBasicMaterial({color:3121622,wireframe:!0});a.frameMesh=new THREE.Mesh(c,b);c=new THREE.PlaneGeometry(a.controls.res,a.controls.res,a.controls.res,a.controls.res);b=new THREE.MeshBasicMaterial({color:3121622,wireframe:!0});c=new THREE.Mesh(c,b);c.position.z-=a.controls.res/2;a.frameMesh.add(c);
a.frameMesh.position.set(a.controls.res/2,a.controls.res/2,a.controls.res/2);a.scene.add(a.frameMesh);a.scene.remove(a.skyBox);c=new THREE.CubeGeometry(2048,2048,2048);b=new THREE.MeshBasicMaterial({map:a.skyBoxTexture,side:THREE.DoubleSide});a.skyBox=new THREE.Mesh(c,b);a.skyBox.position.set(a.controls.res/2,a.controls.res/2,a.controls.res/2);a.scene.add(a.skyBox)};a.onMouseWheel=function(c){if(a.activated){c.preventDefault();var b=0;c.wheelDelta&&(b=c.wheelDelta);c.detail&&(b=-c.detail);a.camera.targetZoom=
0<b?0.9*a.camera.targetZoom:1.1*a.camera.targetZoom;a.camera.targetZoom=Math.max(a.camera.targetZoom,1);a.camera.targetZoom=Math.min(a.camera.targetZoom,256)}};a.addBlock=function(c,b,d,f){c+=0.5;b+=0.5;d+=0.5;void 0==f&&(f=parseInt(a.controls.color.substring(1,7),16));a.widget.blocks[[c,b,d]]={x:c,y:b,z:d,color:f}};a.updateBlocks=function(){a.buildBlocks();a.updateProperWidget()};a.removeBlock=function(c,b,d){delete a.widget.blocks[[c,b,d]]};a.onMouseDown=function(c){if(a.activated&&(c.preventDefault(),
1==c.which&&(a.mouse.down1=!0),2==c.which&&(a.mouse.down2=!0),3==c.which&&(a.mouse.down3=!0),a.mouse.x=c.clientX,a.mouse.y=c.clientY,a.mouse.down1)){a.fastClick=c.ctrlKey&&c.shiftKey?!0:!1;if(c.ctrlKey&&!c.shiftKey)c=a.pick(a.mouse.x,a.mouse.y,!1),null!=c&&(delete a.widget.blocks[c],(new Audio("click.wav")).play(),a.buildBlocks());else if(c.shiftKey&&!c.ctrlKey){var b=parseInt(a.controls.color.substring(1,7),16),c=a.pick(a.mouse.x,a.mouse.y,!0);null!=c&&(a.widget.blocks[c]={x:c[0],y:c[1],z:c[2],color:b},
a.buildBlocks(),a.updateSwatches(a.controls.color),(new Audio("click.wav")).play())}a.updateProperWidget()}};a.updateProperWidget=function(){var c={resolution:a.controls.res,blocks:{}};_.each(a.widget.blocks,function(b){c.blocks[[b.x-a.controls.res/2,b.y-a.controls.res/2,b.z-a.controls.res/2]]={x:b.x-a.controls.res/2,y:b.y-a.controls.res/2,z:b.z-a.controls.res/2,color:b.color}});a.properWidget=c};a.updateSwatches=function(c){for(var b=-1,d=0;16>d;d++)if(a.swatches[d].color==c){b=d;break}if(-1==b){for(d=
15;0<d;d--)a.swatches[d].color=a.swatches[d-1].color,a.swatches[d].style.background=a.swatches[d-1].color;a.swatches[0].color=c;a.swatches[0].style.background=c}else if(0<b){for(d=b;0<d;d--)a.swatches[d].color=a.swatches[d-1].color,a.swatches[d].style.background=a.swatches[d-1].color;a.swatches[0].color=c;a.swatches[0].style.background=c}};a.onMouseUp=function(c){a.activated&&(1==c.which&&(a.mouse.down1=!1),2==c.which&&(a.mouse.down2=!1),3==c.which&&(a.mouse.down3=!1))};a.onMouseMove=function(c){if(a.activated){c.preventDefault();
var b=c.clientX-a.mouse.x,d=c.clientY-a.mouse.y;a.mouse.x=c.clientX;a.mouse.y=c.clientY;a.mouse.down1&&(!c.shiftKey&&!c.ctrlKey)&&(a.camera.targetYaw-=0.01*b,a.camera.targetPitch+=0.01*d)}};a.setWidget=function(c){gWidgets.requestWidget(c,function(b){a.controls.tags=b.tags.join(" ");a.controls.res=b.resolution;a.setResolution();var c={resolution:b.resolution,blocks:{}};_.each(b.blocks,function(d){c.blocks[[d.x+b.resolution/2,d.y+b.resolution/2,d.z+b.resolution/2]]={x:d.x+b.resolution/2,y:d.y+b.resolution/
2,z:d.z+b.resolution/2,color:d.color};a.updateSwatches("#"+d.color.toString(16))});a.widget=c;a.buildBlocks()})};a.render=function(){if(a.activated){a.skyBox.rotation.x+=1E-4;a.skyBox.rotation.y+=1.1E-4;a.skyBox.rotation.z+=1.2E-4;a.camera.targetPitch=Math.max(a.camera.targetPitch,-0.99*Math.PI/2);a.camera.targetPitch=Math.min(a.camera.targetPitch,0.99*Math.PI/2);a.camera.pitch+=0.5*(a.camera.targetPitch-a.camera.pitch);a.camera.yaw+=0.5*(a.camera.targetYaw-a.camera.yaw);a.camera.zoom+=0.25*(a.camera.targetZoom-
a.camera.zoom);a.camera.position.set(a.camera.zoom*Math.cos(a.camera.yaw)*Math.cos(a.camera.pitch)+a.controls.res/2,a.camera.zoom*Math.sin(a.camera.yaw)*Math.cos(a.camera.pitch)+a.controls.res/2,a.camera.zoom*Math.sin(a.camera.pitch)+a.controls.res/2);a.camera.lookAt(new THREE.Vector3(a.controls.res/2,a.controls.res/2,a.controls.res/2));a.renderer.render(a.scene,a.camera);if(a.fastClick&&a.mouse.down1){var c=parseInt(a.controls.color.substring(1,7),16),b=a.pick(a.mouse.x,a.mouse.y,!0);null!=b&&(a.widget.blocks[b]=
{x:b[0],y:b[1],z:b[2],color:c},a.buildBlocks(),a.updateSwatches(a.controls.color),(new Audio("click.wav")).play());a.updateProperWidget()}requestAnimationFrame(a.render)}};a.initialize()};
